theme = "gruvbox_material_dark_hard"

[editor]
mouse = true
scroll-lines = 3
shell = ["fish", "-c"]
line-number = "relative"
cursorline = true
gutters = ["line-numbers", "diagnostics", "diff"]
rulers = [80]
bufferline = "always"
color-modes = true
text-width = 80
continue-comments = false
end-of-line-diagnostics = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "│"

# [editor.inline-diagnostics]
# other-lines = "error"

[editor.lsp]
display-messages = true
display-progress-messages = true

[editor.soft-wrap]
enable = false
wrap-at-text-width = true
wrap-indicator = ""

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = "·"
